#!/usr/bin/env python3
"""W12 documentation/spec synchronization helpers."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
ANCHOR_MAP = ROOT / "docs/engineering/spec-anchor-map-v1.md"
ANCHOR_SOURCE_GLOBS = [
    "README.md",
    "amber_unified_final_spec.md",
    "docs/engineering/*.md",
    "spec/changelog/*.md",
]
ANCHOR_SOURCE_EXCLUDES = {
    "docs/engineering/spec-anchor-map-v1.md",
}
REGISTRY_GLOBS = [
    "spec/registries/*.yaml",
]
LINK_SCAN_GLOBS = [
    "README.md",
    "amber_unified_final_spec.md",
    "docs/engineering/*.md",
    "spec/changelog/*.md",
]

HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")
FENCE_RE = re.compile(r"^```")
SPEC_ANCHOR_RE = re.compile(r"^spec_anchor:\s*(\S+)\s*$")


@dataclass(frozen=True)
class Heading:
    path: Path
    line: int
    level: int
    title: str
    anchor: str


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def table_escape(value: object) -> str:
    return str(value).replace("|", r"\|").replace("\n", " ")


def source_files(patterns: Iterable[str], excludes: set[str] | None = None) -> list[Path]:
    excludes = excludes or set()
    files: list[Path] = []
    seen: set[str] = set()
    for pattern in patterns:
        for path in sorted(ROOT.glob(pattern)):
            if not path.is_file():
                continue
            relative = rel(path)
            if relative in excludes or relative in seen:
                continue
            files.append(path)
            seen.add(relative)
    return files


def strip_inline_markup(title: str) -> str:
    title = re.sub(r"<[^>]+>", "", title)
    title = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", title)
    return title.replace("`", "").replace("*", "").replace("_", "").strip()


def anchor_base(title: str) -> str:
    normalized = strip_inline_markup(title).lower()
    chars: list[str] = []
    for char in normalized:
        if char.isalnum() or char in {" ", "-", "_"}:
            chars.append(char)
        elif char.isspace():
            chars.append(" ")
    slug = re.sub(r"\s+", "-", "".join(chars).strip())
    slug = re.sub(r"-+", "-", slug)
    return slug or "section"


def headings_for(path: Path, emit_level: int = 2) -> list[Heading]:
    headings: list[Heading] = []
    used: dict[str, int] = {}
    in_fence = False
    for index, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = HEADING_RE.match(line)
        if not match:
            continue
        level = len(match.group(1))
        title = match.group(2).strip()
        base = anchor_base(title)
        previous = used.get(base, 0)
        used[base] = previous + 1
        anchor = base if previous == 0 else f"{base}-{previous}"
        if level <= emit_level:
            headings.append(Heading(path, index, level, title, anchor))
    return headings


def anchor_index() -> dict[str, set[str]]:
    index: dict[str, set[str]] = {}
    for path in source_files(ANCHOR_SOURCE_GLOBS):
        anchors = {heading.anchor for heading in headings_for(path, emit_level=6)}
        index[rel(path)] = anchors
    return index


def registry_rows() -> list[tuple[str, int, str]]:
    rows: list[tuple[str, int, str]] = []
    for path in source_files(REGISTRY_GLOBS):
        data = path.read_bytes()
        lines = path.read_text(encoding="utf-8").count("\n")
        rows.append((rel(path), lines, hashlib.sha256(data).hexdigest()))
    return rows


def generate_anchor_map() -> str:
    markdown: list[str] = [
        "# amber.spec-anchor-map.v1",
        "",
        "Status: generated W12 anchor map for the current repository docs/spec set.",
        "",
        "Generated by `python3 tools/spec_sync.py anchor-map`.",
        "Check with `make spec-sync-check`.",
        "",
        "## Source Set",
        "",
        "| Source | Included headings |",
        "| --- | ---: |",
    ]

    sources = source_files(ANCHOR_SOURCE_GLOBS, ANCHOR_SOURCE_EXCLUDES)
    all_headings: list[Heading] = []
    for path in sources:
        headings = headings_for(path, emit_level=2)
        all_headings.extend(headings)
        markdown.append(f"| `{table_escape(rel(path))}` | {len(headings)} |")

    markdown.extend(
        [
            "",
            "## Registry Inventory",
            "",
            "| Registry | Lines | SHA-256 |",
            "| --- | ---: | --- |",
        ]
    )
    for path, lines, digest in registry_rows():
        markdown.append(f"| `{table_escape(path)}` | {lines} | `{digest}` |")

    markdown.extend(
        [
            "",
            "## Anchor Map",
            "",
            "| Source | Line | Level | Anchor | Heading |",
            "| --- | ---: | ---: | --- | --- |",
        ]
    )
    for heading in all_headings:
        path = rel(heading.path)
        link = f"../../{path}#{heading.anchor}"
        source_link = f"[`{table_escape(path)}`](../../{path})"
        anchor_link = f"[`{table_escape(heading.anchor)}`]({link})"
        markdown.append(
            "| "
            + f"{source_link} | {heading.line} | {heading.level} | "
            + f"{anchor_link} | {table_escape(heading.title)} |"
        )

    markdown.append("")
    return "\n".join(markdown)


def strip_fenced_code(markdown: str) -> str:
    kept: list[str] = []
    in_fence = False
    for line in markdown.splitlines():
        if FENCE_RE.match(line):
            in_fence = not in_fence
            kept.append("")
            continue
        kept.append("" if in_fence else line)
    return "\n".join(kept)


def strip_line_suffix(path: Path) -> Path:
    text = str(path)
    match = re.match(r"^(.*):(\d+)$", text)
    if match and not path.exists():
        return Path(match.group(1))
    return path


def resolve_link(source: Path, target: str) -> tuple[Path | None, str | None]:
    target = target.strip()
    if target.startswith("<") and target.endswith(">"):
        target = target[1:-1]
    target = target.split(" ", 1)[0]
    if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target):
        return None, None
    path_part, _, anchor = target.partition("#")
    if not path_part:
        return source, anchor or None
    if path_part.startswith("/"):
        path = Path(path_part)
    else:
        path = (source.parent / path_part).resolve()
    return strip_line_suffix(path), anchor or None


def check_links() -> list[str]:
    errors: list[str] = []
    anchors = anchor_index()
    for source in source_files(LINK_SCAN_GLOBS):
        text = strip_fenced_code(source.read_text(encoding="utf-8"))
        for target in MARKDOWN_LINK_RE.findall(text):
            resolved, anchor = resolve_link(source, target)
            if resolved is None:
                continue
            if not resolved.exists():
                errors.append(f"{rel(source)}: missing link target {target}")
                continue
            try:
                resolved_rel = rel(resolved)
            except ValueError:
                continue
            if anchor and resolved.suffix.lower() in {".md", ".markdown"}:
                available = anchors.get(resolved_rel)
                if available is not None and anchor not in available:
                    errors.append(
                        f"{rel(source)}: missing anchor #{anchor} in {resolved_rel}"
                    )
    return errors


def check_registry_anchors() -> list[str]:
    errors: list[str] = []
    for registry in source_files(REGISTRY_GLOBS):
        for index, line in enumerate(registry.read_text(encoding="utf-8").splitlines(), 1):
            match = SPEC_ANCHOR_RE.match(line)
            if not match:
                continue
            target = match.group(1)
            candidates = [ROOT / target, ROOT / "spec_history" / target]
            if not any(candidate.exists() for candidate in candidates):
                errors.append(f"{rel(registry)}:{index}: stale spec_anchor {target}")
    return errors


def cmd_anchor_map(_: argparse.Namespace) -> int:
    sys.stdout.write(generate_anchor_map())
    return 0


def cmd_check(_: argparse.Namespace) -> int:
    errors: list[str] = []
    expected = generate_anchor_map()
    if not ANCHOR_MAP.exists():
        errors.append(f"missing generated anchor map: {rel(ANCHOR_MAP)}")
    elif ANCHOR_MAP.read_text(encoding="utf-8") != expected:
        errors.append(
            "generated anchor map is stale; run "
            "`python3 tools/spec_sync.py anchor-map > docs/engineering/spec-anchor-map-v1.md`"
        )
    errors.extend(check_links())
    errors.extend(check_registry_anchors())
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    print("spec sync docs are current")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    anchor_parser = subparsers.add_parser("anchor-map")
    anchor_parser.set_defaults(func=cmd_anchor_map)
    check_parser = subparsers.add_parser("check")
    check_parser.set_defaults(func=cmd_check)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
